name: Publish NuGet Package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet build --configuration Release --no-restore

    - name: Pack the project
      run: dotnet pack AuthProvider/ --configuration Release --no-build --output ./nupkg

    - name: Publish to GitHub Packages
      run: dotnet nuget push ./nupkg/*.nupkg --source https://nuget.pkg.github.com/Unicycle-Unicorn/index.json --api-key ${{ secrets.GITHUB_TOKEN }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
